### ISSUE TITLE
Error of array shape in Dashboard.py

### ISSUE THREAD

**Issue by Thomas4390** [Thomas4390/Finance-NLP#1]
All good for others stocks like AOS, AAPL, etc.. But for example, MMM can't load the data due to a different array shape. 

Detail of the error : 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/streamlit/scriptrunner/script_runner.py", line 554, in _run_script
    exec(code, module.__dict__)
  File "pages/Dashboard.py", line 83, in <module>
    df.loc[df.index[i]] = data_numbers_flat[start:end]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 716, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1690, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/indexing.py", line 1938, in _setitem_single_block
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 337, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 304, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 941, in setitem
    values[indexer] = value
ValueError: could not broadcast input array from shape (4,) into shape (5,)

**Comment by Thomas4390** [comment]
The problem arises when there are missing values in the "Income Statement" table. Therefore, a way must be found to replace the missing values with NaN values, for example
